### ISSUE TITLE
After update to 7.0.0 Android crashes immediately

### ISSUE THREAD

**Issue by philipe-grendene** [oracle/pushiomanager-react-native#75]
**Issue Description:**
We are encountering a NoSuchMethodError when using the @oracle/react-native-pushiomanager module, version 7.0.0, in our React Native application. This issue is specific to Android devices.

obs: it was working in previous version as it should.

The error stack trace is as follows:

<img width="2105" alt="Image" src="https://github.com/user-attachments/assets/5b43664d-8326-43a3-898c-a5a3e1c408fd" />

The error is occurring when we try to open the app, the app builds successfully.

Our files related with the lib:

settings.gradle
<img width="1787" alt="Image" src="https://github.com/user-attachments/assets/3137f0be-200a-4b8a-9b3b-ca5bb9997008" />

PushIOManager folder
<img width="411" alt="Image" src="https://github.com/user-attachments/assets/06d2dae9-1eda-40e6-86d4-de804a5d4300" />

app/build.gradle
<img width="1076" alt="Image" src="https://github.com/user-attachments/assets/5a7a57db-6a49-4385-b1ce-ad8126090ce5" />

app/src/main/java/project/MyRNFirebaseMessagingReceiver.java
<img width="1076" alt="Image" src="https://github.com/user-attachments/assets/5065e21b-0e66-4161-bffc-2532cb8ebbe9" />

AndroidManifest.xml
<img width="1456" alt="Image" src="https://github.com/user-attachments/assets/7bff60e8-0f01-417d-9cbd-f4b1dd083dcd" />
<img width="1279" alt="Image" src="https://github.com/user-attachments/assets/c68c4ab9-0d6e-4759-99e5-03554094fb31" />
<img width="1480" alt="Image" src="https://github.com/user-attachments/assets/96379065-615c-4014-9368-ec7d70bc16e6" />
<img width="1568" alt="Image" src="https://github.com/user-attachments/assets/2e2c6c35-3e1a-45ce-8f6f-c94f1c48648b" />
<img width="1068" alt="Image" src="https://github.com/user-attachments/assets/41186ce0-a114-49af-a88a-eaf945d8d288" />

Steps to Reproduce:
Install @oracle/react-native-pushiomanager version 7.0.0.
Then try to run the app
Expected Behavior:
The application loads successfully and is able to receive push notifications.

Actual Behavior:
The app crashes with a NoSuchMethodError when trying to open the app.

Affected Environment:
Library Version: @oracle/react-native-pushiomanager@7.0.0
Platform: Android
React Native Version: 0.76.6
Device Information: Occurs across multiple Android devices.

Please advise if there are any known fixes or workarounds for this issue.
Any guidance on this matter would be greatly appreciated.

Thank you!

**Comment by Prateep-7** [comment]
Facing the same issue
